import icons from "./icons";
import images from "./images";

export { icons, images };

export const categoryData = [
    {
        name: 'Starter',
        image: 'https://themealdb.com/images/category/starter.png'
    },
    {
        name: 'Beef',
        image: 'https://themealdb.com/images/category/beef.png'
    },
    {
        name: 'Dessert',
        image: 'https://themealdb.com/images/category/dessert.png'
    },
    {
        "idCategory": "1",
        "strCategory": "Beef",
        "strCategoryThumb": "https://www.themealdb.com/images/category/beef.png",
        "strCategoryDescription": "Beef is the culinary name for meat from cattle, particularly skeletal muscle. Humans have been eating beef since prehistoric times.[1] Beef is a source of high-quality protein and essential nutrients.[2]"
      },
      {
        "idCategory": "2",
        "strCategory": "Chicken",
        "strCategoryThumb": "https://www.themealdb.com/images/category/chicken.png",
        "strCategoryDescription": "Chicken is a type of domesticated fowl, a subspecies of the red junglefowl. It is one of the most common and widespread domestic animals, with a total population of more than 19 billion as of 2011.[1] Humans commonly keep chickens as a source of food (consuming both their meat and eggs) and, more rarely, as pets."
      },
      {
        "idCategory": "3",
        "strCategory": "Dessert",
        "strCategoryThumb": "https://www.themealdb.com/images/category/dessert.png",
        "strCategoryDescription": "Dessert is a course that concludes a meal. The course usually consists of sweet foods, such as confections dishes or fruit, and possibly a beverage such as dessert wine or liqueur, however in the United States it may include coffee, cheeses, nuts, or other savory items regarded as a separate course elsewhere. In some parts of the world, such as much of central and western Africa, and most parts of China, there is no tradition of a dessert course to conclude a meal.\r\n\r\nThe term dessert can apply to many confections, such as biscuits, cakes, cookies, custards, gelatins, ice creams, pastries, pies, puddings, and sweet soups, and tarts. Fruit is also commonly found in dessert courses because of its naturally occurring sweetness. Some cultures sweeten foods that are more commonly savory to create desserts."
      },
      {
        "idCategory": "4",
        "strCategory": "Lamb",
        "strCategoryThumb": "https://www.themealdb.com/images/category/lamb.png",
        "strCategoryDescription": "Lamb, hogget, and mutton are the meat of domestic sheep (species Ovis aries) at different ages.\r\n\r\nA sheep in its first year is called a lamb, and its meat is also called lamb. The meat of a juvenile sheep older than one year is hogget; outside the USA this is also a term for the living animal. The meat of an adult sheep is mutton, a term only used for the meat, not the living animals. The term mutton is almost always used to refer to goat meat in the Indian subcontinent.\r\n\r\n"
      },
      {
        "idCategory": "5",
        "strCategory": "Miscellaneous",
        "strCategoryThumb": "https://www.themealdb.com/images/category/miscellaneous.png",
        "strCategoryDescription": "General foods that don't fit into another category"
      },
      {
        "idCategory": "6",
        "strCategory": "Pasta",
        "strCategoryThumb": "https://www.themealdb.com/images/category/pasta.png",
        "strCategoryDescription": "Pasta is a staple food of traditional Italian cuisine, with the first reference dating to 1154 in Sicily.\r\n\r\nAlso commonly used to refer to the variety of pasta dishes, pasta is typically a noodle made from an unleavened dough of a durum wheat flour mixed with water or eggs and formed into sheets or various shapes, then cooked by boiling or baking. As an alternative for those wanting a different taste, or who need to avoid products containing gluten, some pastas can be made using rice flour in place of wheat.[3][4] Pastas may be divided into two broad categories, dried (pasta secca) and fresh (pasta fresca)."
      },
      {
        "idCategory": "7",
        "strCategory": "Pork",
        "strCategoryThumb": "https://www.themealdb.com/images/category/pork.png",
        "strCategoryDescription": "Pork is the culinary name for meat from a domestic pig (Sus scrofa domesticus). It is the most commonly consumed meat worldwide,[1] with evidence of pig husbandry dating back to 5000 BC. Pork is eaten both freshly cooked and preserved. Curing extends the shelf life of the pork products. Ham, smoked pork, gammon, bacon and sausage are examples of preserved pork. Charcuterie is the branch of cooking devoted to prepared meat products, many from pork.\r\n\r\nPork is the most popular meat in Eastern and Southeastern Asia, and is also very common in the Western world, especially in Central Europe. It is highly prized in Asian cuisines for its fat content and pleasant texture. Consumption of pork is forbidden by Jewish and Muslim dietary law, a taboo that is deeply rooted in tradition, with several suggested possible causes. The sale of pork is limited in Israel and illegal in certain Muslim countries."
      },
      {
        "idCategory": "8",
        "strCategory": "Seafood",
        "strCategoryThumb": "https://www.themealdb.com/images/category/seafood.png",
        "strCategoryDescription": "Seafood is any form of sea life regarded as food by humans. Seafood prominently includes fish and shellfish. Shellfish include various species of molluscs, crustaceans, and echinoderms. Historically, sea mammals such as whales and dolphins have been consumed as food, though that happens to a lesser extent in modern times. Edible sea plants, such as some seaweeds and microalgae, are widely eaten as seafood around the world, especially in Asia (see the category of sea vegetables). In North America, although not generally in the United Kingdom, the term \"seafood\" is extended to fresh water organisms eaten by humans, so all edible aquatic life may be referred to as seafood. For the sake of completeness, this article includes all edible aquatic life."
      },
      {
        "idCategory": "9",
        "strCategory": "Side",
        "strCategoryThumb": "https://www.themealdb.com/images/category/side.png",
        "strCategoryDescription": "A side dish, sometimes referred to as a side order, side item, or simply a side, is a food item that accompanies the entrée or main course at a meal. Side dishes such as salad, potatoes and bread are commonly used with main courses throughout many countries of the western world. New side orders introduced within the past decade[citation needed], such as rice and couscous, have grown to be quite popular throughout Europe, especially at formal occasions (with couscous appearing more commonly at dinner parties with Middle Eastern dishes)."
      },
      {
        "idCategory": "10",
        "strCategory": "Starter",
        "strCategoryThumb": "https://www.themealdb.com/images/category/starter.png",
        "strCategoryDescription": "An entrée in modern French table service and that of much of the English-speaking world (apart from the United States and parts of Canada) is a dish served before the main course of a meal; it may be the first dish served, or it may follow a soup or other small dish or dishes. In the United States and parts of Canada, an entrée is the main dish or the only dish of a meal.\r\n\r\nHistorically, the entrée was one of the stages of the “Classical Order” of formal French table service of the 18th and 19th centuries. It formed a part of the “first service” of the meal, which consisted of potage, hors d’œuvre, and entrée (including the bouilli and relevé). The “second service” consisted of roast (rôti), salad, and entremets (the entremets sometimes being separated into a “third service” of their own). The final service consisted only of dessert.[3]:3–11 :13–25"
      },
      {
        "idCategory": "11",
        "strCategory": "Vegan",
        "strCategoryThumb": "https://www.themealdb.com/images/category/vegan.png",
        "strCategoryDescription": "Veganism is both the practice of abstaining from the use of animal products, particularly in diet, and an associated philosophy that rejects the commodity status of animals.[b] A follower of either the diet or the philosophy is known as a vegan (pronounced /ˈviːɡən/ VEE-gən). Distinctions are sometimes made between several categories of veganism. Dietary vegans (or strict vegetarians) refrain from consuming animal products, not only meat but also eggs, dairy products and other animal-derived substances.[c] The term ethical vegan is often applied to those who not only follow a vegan diet but extend the philosophy into other areas of their lives, and oppose the use of animals for any purpose.[d] Another term is environmental veganism, which refers to the avoidance of animal products on the premise that the harvesting or industrial farming of animals is environmentally damaging and unsustainable."
      },
      {
        "idCategory": "12",
        "strCategory": "Vegetarian",
        "strCategoryThumb": "https://www.themealdb.com/images/category/vegetarian.png",
        "strCategoryDescription": "Vegetarianism is the practice of abstaining from the consumption of meat (red meat, poultry, seafood, and the flesh of any other animal), and may also include abstention from by-products of animal slaughter.\r\n\r\nVegetarianism may be adopted for various reasons. Many people object to eating meat out of respect for sentient life. Such ethical motivations have been codified under various religious beliefs, as well as animal rights advocacy. Other motivations for vegetarianism are health-related, political, environmental, cultural, aesthetic, economic, or personal preference. There are variations of the diet as well: an ovo-lacto vegetarian diet includes both eggs and dairy products, an ovo-vegetarian diet includes eggs but not dairy products, and a lacto-vegetarian diet includes dairy products but not eggs. A vegan diet excludes all animal products, including eggs and dairy. Some vegans also avoid other animal products such as beeswax, leather or silk clothing, and goose-fat shoe polish."
      },
      {
        "idCategory": "13",
        "strCategory": "Breakfast",
        "strCategoryThumb": "https://www.themealdb.com/images/category/breakfast.png",
        "strCategoryDescription": "Breakfast is the first meal of a day. The word in English refers to breaking the fasting period of the previous night. There is a strong likelihood for one or more \"typical\", or \"traditional\", breakfast menus to exist in most places, but their composition varies widely from place to place, and has varied over time, so that globally a very wide range of preparations and ingredients are now associated with breakfast."
      },
      {
        "idCategory": "14",
        "strCategory": "Goat",
        "strCategoryThumb": "https://www.themealdb.com/images/category/goat.png",
        "strCategoryDescription": "The domestic goat or simply goat (Capra aegagrus hircus) is a subspecies of C. aegagrus domesticated from the wild goat of Southwest Asia and Eastern Europe. The goat is a member of the animal family Bovidae and the subfamily Caprinae, meaning it is closely related to the sheep. There are over 300 distinct breeds of goat. Goats are one of the oldest domesticated species of animal, and have been used for milk, meat, fur and skins across much of the world. Milk from goats is often turned into goat cheese."
      },
]
export const mealData = [
    {
        name: 'Shakshuka',
        image: 'https://themealdb.com/images/media/meals/g373701551450225.jpg'
    },
    {
        name: 'Beef Banh Mi Bowls with Sriracha Mayo',
        image: 'https://themealdb.com/images/media/meals/z0ageb1583189517.jpg'
    },
    {
        name: 'Chickpea Fajitas',
        image: 'https://themealdb.com/images/media/meals/tvtxpq1511464705.jpg'
    },
    {
        name: 'Smokey Lentil Chili With Squash',
        image: 'https://themealdb.com/images/media/meals/uwxqwy1483389553.jpg'
    },
    {
        name:'Traditional Pound Cake',
        image:'https://bromabakery.com/wp-content/uploads/2023/05/Classic-Pound-Cake-1067x1600.webp',
    },
    {
        name:'Spanish Flan',
        image:'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F691985.jpg&q=60&c=sc&poi=auto&orient=true&h=512',
    },
    {
        name:'Chicken Teriyaki',
        image:'https://www.cookingclassy.com/wp-content/uploads/2018/04/teriyaki-chicken-15.jpg',
    },
    {
        "idMeal": "52970",
        "strMeal": "Tunisian Orange Cake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "Tunisian",
        "strInstructions": "Preheat oven to 190 C / Gas 5. Grease a 23cm round springform tin.\r\nCut off the hard bits from the top and bottom of the orange. Slice the orange and remove all seeds. Puree the orange with its peel in a food processor. Add one third of the sugar and the olive oil and continue to mix until well combined.\r\nSieve together flour and baking powder.\r\nBeat the eggs and the remaining sugar with an electric hand mixer for at least five minutes until very fluffy. Fold in half of the flour mixture, then the orange and the vanilla, then fold in the remaining flour. Mix well but not for too long.\r\nPour cake mixture into prepared tin and smooth out. Bake in preheated oven for 20 minutes. Reduce the oven temperature to 160 C / Gas 2 and bake again for 30 minutes Bake until the cake is golden brown and a skewer comes out clean. Cool on a wire cake rack.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/y4jpgq1560459207.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=rCUxg866Ea4",
        "strIngredient1": "Orange",
        "strIngredient2": "Caster Sugar",
        "strIngredient3": "Olive Oil",
        "strIngredient4": "Flour",
        "strIngredient5": "Baking Powder",
        "strIngredient6": "Eggs",
        "strIngredient7": "Vanilla Extract",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1 large",
        "strMeasure2": "300g",
        "strMeasure3": "75 ml ",
        "strMeasure4": "280g",
        "strMeasure5": "1 tbs",
        "strMeasure6": "4 large",
        "strMeasure7": "2 tsp",
        "strMeasure8": " ",
        "strMeasure9": " ",
        "strMeasure10": " ",
        "strMeasure11": " ",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "http://allrecipes.co.uk/recipe/16067/tunisian-orange-cake.aspx",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52883",
        "strMeal": "Sticky Toffee Pudding",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Preheat the oven to 180C/160C Fan/Gas 4. Butter a wide shallow 1.7-litre/3-pint ovenproof dish.\r\nPut the butter, sugar, eggs, flour, baking powder, bicarbonate of soda and treacle into a mixing bowl. Beat using an electric handheld whisk for about 30 seconds or until combined. Pour in the milk gradually and whisk again until smooth. Pour into the prepared dish. Bake for 35–40 minutes or until well risen and springy in the centre.\r\nTo make the sauce, put all the ingredients into a saucepan and stir over a low heat until the sugar has dissolved and the butter has melted. Bring to the boil, stirring for a minute.\r\nTo serve, pour half the sauce over the pudding in the baking dish. Serve with the cream or ice cream.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/xqqqtu1511637379.jpg",
        "strTags": "Pudding,Cake,Desert",
        "strYoutube": "https://www.youtube.com/watch?v=Wytv3bjqJII",
        "strIngredient1": "Butter",
        "strIngredient2": "Muscovado Sugar",
        "strIngredient3": "Eggs",
        "strIngredient4": "Self-raising Flour",
        "strIngredient5": "Baking Powder",
        "strIngredient6": "Bicarbonate Of Soda",
        "strIngredient7": "Black Treacle",
        "strIngredient8": "Milk",
        "strIngredient9": "Double Cream",
        "strIngredient10": "Butter",
        "strIngredient11": "Muscovado Sugar",
        "strIngredient12": "Black Treacle",
        "strIngredient13": "Double Cream",
        "strIngredient14": "Vanilla Extract",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "100g ",
        "strMeasure2": "175g",
        "strMeasure3": "2 large",
        "strMeasure4": "225g",
        "strMeasure5": "1 tsp ",
        "strMeasure6": "1 tsp ",
        "strMeasure7": "3 tbs",
        "strMeasure8": "275ml",
        "strMeasure9": "to serve",
        "strMeasure10": "100g ",
        "strMeasure11": "125g",
        "strMeasure12": "1 tbs",
        "strMeasure13": "300ml ",
        "strMeasure14": "1 tsp ",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbc.co.uk/food/recipes/marys_sticky_toffee_41970",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52923",
        "strMeal": "Canadian Butter Tarts",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "Canadian",
        "strInstructions": "Preheat the oven to fan 170C/ conventional 190C/gas 5. Roll out the pastry on a lightly floured surface so it’s slightly thinner than straight from the pack. Then cut out 18-20 rounds with a 7.5cm fluted cutter, re-rolling the trimmings. Use the rounds to line two deep 12-hole tart tins (not muffin tins). If you only have a regular-sized, 12-hole tart tin you will be able to make a few more slightly shallower tarts.\r\nBeat the eggs in a large bowl and combine with the rest of the ingredients except the walnuts. Tip this mixture into a pan and stir continuously for 3-4 minutes until the butter melts, and the mixture bubbles and starts to thicken. It should be thick enough to coat the back of a wooden spoon. Don’t overcook, and be sure to stir all the time as the mixture can easily burn. Remove from the heat and stir in the nuts.\r\nSpoon the filling into the unbaked tart shells so it’s level with the pastry. Bake for 15-18 minutes until set and pale golden. Leave in the tin to cool for a few minutes before lifting out on to a wire rack. Serve warm or cold.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/wpputp1511812960.jpg",
        "strTags": "Speciality,Snack,Desert,Pudding",
        "strYoutube": "https://www.youtube.com/watch?v=WUpaOGghOdo",
        "strIngredient1": "Shortcrust Pastry",
        "strIngredient2": "Eggs",
        "strIngredient3": "Muscovado Sugar",
        "strIngredient4": "Raisins",
        "strIngredient5": "Vanilla Extract",
        "strIngredient6": "Butter",
        "strIngredient7": "Single Cream",
        "strIngredient8": "Walnuts",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "375g",
        "strMeasure2": "2 large",
        "strMeasure3": "175g",
        "strMeasure4": "100g ",
        "strMeasure5": "1 tsp ",
        "strMeasure6": "50g",
        "strMeasure7": "4 tsp",
        "strMeasure8": "50g",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/1837/canadian-butter-tarts",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52796",
        "strMeal": "Chicken Alfredo Primavera",
        "strDrinkAlternate": null,
        "strCategory": "Chicken",
        "strArea": "Italian",
        "strInstructions": "Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat. Season both sides of each chicken breast with seasoned salt and a pinch of pepper. Add the chicken to the skillet and cook for 5-7 minutes on each side, or until cooked through.  While the chicken is cooking, bring a large pot of water to a boil. Season the boiling water with a few generous pinches of kosher salt. Add the pasta and give it a stir. Cook, stirring occasionally, until al dente, about 12 minutes. Reserve 1/2 cup of  pasta water before draining the pasta.  Remove the chicken from the pan and transfer it to a cutting board; allow it to rest. Turn the heat down to medium and dd the remaining 1 tablespoon of butter and olive oil to the same pan you used to cook the chicken. Add the veggies (minus the garlic) and red pepper flakes to the pan and stir to coat with the oil and butter (refrain from seasoning with salt until the veggies are finished browning). Cook, stirring often, until the veggies are tender, about 5 minutes. Add the garlic and a generous pinch of salt and pepper to the pan and cook for 1 minute.  Deglaze the pan with the white wine. Continue to cook until the wine has reduced by half, about 3 minutes. Stir in the milk, heavy cream, and reserved pasta water. Bring the mixture to a gentle boil and allow to simmer and reduce for 2-3 minutes. Turn off the heat and add the Parmesan cheese and cooked pasta. Season with salt and pepper to taste. Garnish with Parmesan cheese and chopped parsley, if desired. ",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
        "strTags": "Pasta,Meat,Dairy",
        "strYoutube": "https://www.youtube.com/watch?v=qCIbq8HywpQ",
        "strIngredient1": "Butter",
        "strIngredient2": "Olive Oil",
        "strIngredient3": "Chicken",
        "strIngredient4": "Salt",
        "strIngredient5": "Squash",
        "strIngredient6": "Broccoli",
        "strIngredient7": "mushrooms",
        "strIngredient8": "Pepper",
        "strIngredient9": "onion",
        "strIngredient10": "garlic",
        "strIngredient11": "red pepper flakes",
        "strIngredient12": "white wine",
        "strIngredient13": "milk",
        "strIngredient14": "heavy cream",
        "strIngredient15": "Parmesan cheese",
        "strIngredient16": "bowtie pasta",
        "strIngredient17": "Salt",
        "strIngredient18": "Pepper",
        "strIngredient19": "Parsley",
        "strIngredient20": "",
        "strMeasure1": "2 tablespoons",
        "strMeasure2": "3 tablespoons",
        "strMeasure3": "5 boneless",
        "strMeasure4": "1 teaspoon",
        "strMeasure5": "1 cut into 1/2-inch cubes",
        "strMeasure6": "1 Head chopped",
        "strMeasure7": "8-ounce sliced",
        "strMeasure8": "1 red",
        "strMeasure9": "1 chopped",
        "strMeasure10": "3 cloves",
        "strMeasure11": "1/2 teaspoon",
        "strMeasure12": "1/2 cup",
        "strMeasure13": "1/2 cup",
        "strMeasure14": "1/2 cup",
        "strMeasure15": "1 cup grated",
        "strMeasure16": "16 ounces",
        "strMeasure17": "pinch",
        "strMeasure18": "pinch ",
        "strMeasure19": "chopped",
        "strMeasure20": "",
        "strSource": "",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52922",
        "strMeal": "Prawn & Fennel Bisque",
        "strDrinkAlternate": null,
        "strCategory": "Side",
        "strArea": "French",
        "strInstructions": "Shell the prawns, then fry the shells in the oil in a large pan for about 5 mins. Add the onion, fennel and carrots and cook for about 10 mins until the veg start to soften. Pour in the wine and brandy, bubble hard for about 1 min to drive off the alcohol, then add the tomatoes, stock and paprika. Cover and simmer for 30 mins. Meanwhile, chop the prawns.\r\nBlitz the soup as finely as you can with a stick blender or food processor, then press through a sieve into a bowl. Spend a bit of time really working the mixture through the sieve as this will give the soup its velvety texture.\r\nTip back into a clean pan, add the prawns and cook for 10 mins, then blitz again until smooth. You can make and chill this a day ahead or freeze it for 1 month. Thaw ovenight in the fridge. To serve, gently reheat in a pan with the cream. If garnishing, cook the 8 prawns in a little butter. Spoon into small bowls and top with the prawns and snipped fennel fronds.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/rtwwvv1511799504.jpg",
        "strTags": "Soup,Warm,Seafood,Shellfish",
        "strYoutube": "https://www.youtube.com/watch?v=4thpMbDakgM",
        "strIngredient1": "Tiger Prawns",
        "strIngredient2": "Olive Oil",
        "strIngredient3": "Onion",
        "strIngredient4": "Fennel",
        "strIngredient5": "Carrots",
        "strIngredient6": "Dry White Wine",
        "strIngredient7": "Brandy",
        "strIngredient8": "Chopped Tomatoes",
        "strIngredient9": "Fish Stock",
        "strIngredient10": "Paprika",
        "strIngredient11": "Double Cream",
        "strIngredient12": "Prawns",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "450g",
        "strMeasure2": "4 tbs",
        "strMeasure3": "1 large",
        "strMeasure4": "1 large",
        "strMeasure5": "2 chopped",
        "strMeasure6": "150ml",
        "strMeasure7": "1 tbs",
        "strMeasure8": "400g",
        "strMeasure9": "1L",
        "strMeasure10": "2 pinches",
        "strMeasure11": "150ml",
        "strMeasure12": "8",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/71600/prawn-and-fennel-bisque",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52805",
        "strMeal": "Lamb Biryani",
        "strDrinkAlternate": null,
        "strCategory": "Lamb",
        "strArea": "Indian",
        "strInstructions": "Grind the cashew, poppy seeds and cumin seeds into a smooth paste, using as little water as possible. Set aside. \r\n\r\nDeep fry the sliced onions when it is hot. Don’t overcrowd the oil. When the onions turn light brown, remove from oil and drain on paper towel. The fried onion will crisp up as it drains. Also fry the cashewnuts till golden brown. Set aside.\r\n\r\nWash the rice and soak in water for twenty minutes.\r\nMeanwhile, take a big wide pan, add oil in medium heat, add the sliced onions, add the blended paste, to it add the green chillies, ginger garlic paste and garlic and fry for a minute.\r\nThen add the tomatoes and sauté them well till they are cooked and not mushy.\r\n\r\nThen to it add the red chilli powder, biryani powder, mint, coriander leaves and sauté them well.\r\nAdd the yogurt and mix well. I always move the skillet away from the heat when adding yogurt which prevents it from curdling.\r\n\r\nNow after returning the skillet back to the stove, add the washed lamb and salt and ½ cup water and mix well. Cook for 1 hour and cook it covered in medium low heat or put it in a pressure cooker for 6 whistles. If the water is not drained totally, heat it by keeping it open.\r\n\r\nTake another big pan, add thrice the cup of rice you use, and boil it. When it is boiling high, add the rice, salt and jeera and mix well. After 7 minutes exact or when the rice is 80% done. Switch off and drain the rice.\r\n\r\nNow, the layering starts. To the lamb, pat and level it. Add the drained hot rice on the top of it. Garnish with fried onions, ghee, mint, coriander leaves and saffron dissolved in milk.\r\n\r\nCover the dish and bake in a 350f oven for 15 minutes or till the cooked but not mushy. Or cook in the stove medium heat for 12 minutes and lowest heat for 5 minutes. And switch off. Mix and serve hot!\r\nNotes\r\n1. If you are cooking in oven, do make sure to cook in a big oven safe pan and cover it tight and then keep in oven for the final step.\r\n2. You can skip biryani masala if you don’t have and add just garam masala (1 tsp and red chilli powder – 3 tsp instead of 1 tsp)\r\n3. If it is spicy in the end, squeeze some lemon, it will reduce the heat and enhance the flavors also.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
        "strTags": "Curry,Meat",
        "strYoutube": "https://www.youtube.com/watch?v=r7SYVSG5nxo",
        "strIngredient1": "Cashew nuts",
        "strIngredient2": "Khus khus",
        "strIngredient3": "Cumin seeds",
        "strIngredient4": "Onions",
        "strIngredient5": "Ginger garlic paste",
        "strIngredient6": "Garlic",
        "strIngredient7": "Mint",
        "strIngredient8": "Cilantro",
        "strIngredient9": "Saffron",
        "strIngredient10": "Ghee",
        "strIngredient11": "Basmati rice",
        "strIngredient12": "Full fat yogurt",
        "strIngredient13": "Cumin Seeds",
        "strIngredient14": "Bay leaf",
        "strIngredient15": "Cinnamon",
        "strIngredient16": "Cloves",
        "strIngredient17": "Cardamom",
        "strIngredient18": "Lamb",
        "strIngredient19": "Red Chilli powder",
        "strIngredient20": "Biryani masala",
        "strMeasure1": "12",
        "strMeasure2": "½ tbsp",
        "strMeasure3": "½ tbsp",
        "strMeasure4": "3 sliced thinly",
        "strMeasure5": "2 tsp",
        "strMeasure6": "4 whole",
        "strMeasure7": "Leaves",
        "strMeasure8": "Leaves",
        "strMeasure9": "½ tsp dissolved in ½ cup warm milk",
        "strMeasure10": "2 tbsp",
        "strMeasure11": "2 Cups",
        "strMeasure12": "½ cup",
        "strMeasure13": "1 tbsp",
        "strMeasure14": "½",
        "strMeasure15": "1 thin piece",
        "strMeasure16": "3",
        "strMeasure17": "2",
        "strMeasure18": "1 lb",
        "strMeasure19": "1 tsp",
        "strMeasure20": "1 tbsp",
        "strSource": "http://www.relishthebite.com/restaurant-style-lamb-biryani/",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52921",
        "strMeal": "Provençal Omelette Cake",
        "strDrinkAlternate": null,
        "strCategory": "Vegetarian",
        "strArea": "French",
        "strInstructions": "Break the eggs into two bowls, five in each. Whisk lightly and season with salt and pepper. Heat the oil in a pan, add the courgettes and spring onions, then fry gently for about 10 mins until softened. Cool, then stir into one bowl of eggs with a little salt and pepper. Add the roasted peppers to the other bowl of eggs with the garlic, chilli, salt and pepper.\r\nHeat a little oil in a 20-23cm frying pan, preferably non-stick. Pour the eggs with courgette into a measuring jug, then pourabout one-third of the mixture into the pan, swirling it to cover the base of the pan. Cook until the egg is set and lightly browned underneath, then cover the pan with a plate and invert the omelette onto it. Slide it back into the pan to cook the other side. Repeat with the remaining mix to make two more omelettes, adding a little oil to the pan each time. Stack the omelettes onto a plate. Make three omelettes in the same way with the red pepper mixture, then stack them on a separate plate.\r\nNow make the filling. Beat the cheese to soften it, then beat in the milk to make a spreadable consistency. Stir in the herbs, salt and pepper. Line a deep, 20-23cm round cake tin with cling film (use a tin the same size as the frying pan). Select the best red pepper omelette and place in the tin, prettiest side down. Spread with a thin layer of cheese filling, then cover with a courgette omelette. Repeat, alternating the layers, until all the omelettes and filling are in the tin, finishing with an omelette. Flip the cling film over the omelette, then chill for up to 24 hrs.\r\nTo serve, invert the omelette cake onto a serving plate and peel off the cling film. Pile rocket on the top and scatter over the cheese, a drizzle of olive oil and a little freshly ground black pepper. Serve cut into wedges.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qwtrtp1511799242.jpg",
        "strTags": "Egg",
        "strYoutube": "https://www.youtube.com/watch?v=B7isFo2uP2k",
        "strIngredient1": "Eggs",
        "strIngredient2": "Olive Oil",
        "strIngredient3": "Courgettes",
        "strIngredient4": "Spring Onions",
        "strIngredient5": "Red Pepper",
        "strIngredient6": "Garlic Clove",
        "strIngredient7": "Red Chilli",
        "strIngredient8": "Cream Cheese",
        "strIngredient9": "Milk",
        "strIngredient10": "Chives",
        "strIngredient11": "Basil",
        "strIngredient12": "Rocket",
        "strIngredient13": "Parmesan",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "10",
        "strMeasure2": "1 tbs",
        "strMeasure3": "2 finely chopped",
        "strMeasure4": "3 finely chopped",
        "strMeasure5": "4",
        "strMeasure6": "1 clove peeled crushed",
        "strMeasure7": "1",
        "strMeasure8": "300g",
        "strMeasure9": "6 tblsp",
        "strMeasure10": "4 tbs",
        "strMeasure11": "2 tbs",
        "strMeasure12": "to serve",
        "strMeasure13": "to serve",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/6428/provenal-omelette-cake",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "52920",
        "strMeal": "Chicken Marengo",
        "strDrinkAlternate": null,
        "strCategory": "Chicken",
        "strArea": "French",
        "strInstructions": "Heat the oil in a large flameproof casserole dish and stir-fry the mushrooms until they start to soften. Add the chicken legs and cook briefly on each side to colour them a little.\r\nPour in the passata, crumble in the stock cube and stir in the olives. Season with black pepper – you shouldn’t need salt. Cover and simmer for 40 mins until the chicken is tender. Sprinkle with parsley and serve with pasta and a salad, or mash and green veg, if you like.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=U33HYUr-0Fw",
        "strIngredient1": "Olive Oil",
        "strIngredient2": "Mushrooms",
        "strIngredient3": "Chicken Legs",
        "strIngredient4": "Passata",
        "strIngredient5": "Chicken Stock Cube",
        "strIngredient6": "Black Olives",
        "strIngredient7": "Parsley",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1 tbs",
        "strMeasure2": "300g",
        "strMeasure3": "4",
        "strMeasure4": "500g",
        "strMeasure5": "1",
        "strMeasure6": "100g ",
        "strMeasure7": "Chopped",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/3146682/chicken-marengo",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "53053",
        "strMeal": "Beef Rendang",
        "strDrinkAlternate": null,
        "strCategory": "Beef",
        "strArea": "Malaysian",
        "strInstructions": "Chop the spice paste ingredients and then blend it in a food processor until fine.\r\nHeat the oil in a stew pot, add the spice paste, cinnamon, cloves, star anise, and cardamom and stir-fry until aromatic. Add the beef and the pounded lemongrass and stir for 1 minute. Add the coconut milk, tamarind juice, water, and simmer on medium heat, stirring frequently until the meat is almost cooked. Add the kaffir lime leaves, kerisik (toasted coconut), sugar or palm sugar, stirring to blend well with the meat.\r\nLower the heat to low, cover the lid, and simmer for 1 to 1 1/2 hours or until the meat is really tender and the gravy has dried up. Add more salt and sugar to taste. Serve immediately with steamed rice and save some for overnight.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=Ot-dmfBaZrA",
        "strIngredient1": "Beef",
        "strIngredient2": "Vegetable Oil",
        "strIngredient3": "Cinnamon Stick",
        "strIngredient4": "Cloves",
        "strIngredient5": "Star Anise",
        "strIngredient6": "Cardamom",
        "strIngredient7": "Coconut Cream",
        "strIngredient8": "Water",
        "strIngredient9": "Tamarind Paste",
        "strIngredient10": "Lime",
        "strIngredient11": "Sugar",
        "strIngredient12": "Challots",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1lb",
        "strMeasure2": "5 tbs",
        "strMeasure3": "1",
        "strMeasure4": "3",
        "strMeasure5": "3",
        "strMeasure6": "3",
        "strMeasure7": "1 cup ",
        "strMeasure8": "1 cup ",
        "strMeasure9": "2 tbs",
        "strMeasure10": "6",
        "strMeasure11": "1 tbs",
        "strMeasure12": "5",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "https://rasamalaysia.com/beef-rendang-recipe-rendang-daging/",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },
      {
        "idMeal": "53014",
        "strMeal": "Pizza Express Margherita",
        "strDrinkAlternate": null,
        "strCategory": "Miscellaneous",
        "strArea": "Italian",
        "strInstructions": "1 Preheat the oven to 230°C.\r\n\r\n2 Add the sugar and crumble the fresh yeast into warm water.\r\n\r\n3 Allow the mixture to stand for 10 – 15 minutes in a warm place (we find a windowsill on a sunny day works best) until froth develops on the surface.\r\n\r\n4 Sift the flour and salt into a large mixing bowl, make a well in the middle and pour in the yeast mixture and olive oil.\r\n\r\n5 Lightly flour your hands, and slowly mix the ingredients together until they bind.\r\n\r\n6 Generously dust your surface with flour.\r\n\r\n7 Throw down the dough and begin kneading for 10 minutes until smooth, silky and soft.\r\n\r\n8 Place in a lightly oiled, non-stick baking tray (we use a round one, but any shape will do!)\r\n\r\n9 Spread the passata on top making sure you go to the edge.\r\n\r\n10 Evenly place the mozzarella (or other cheese) on top, season with the oregano and black pepper, then drizzle with a little olive oil.\r\n\r\n11 Cook in the oven for 10 – 12 minutes until the cheese slightly colours.\r\n\r\n12 When ready, place the basil leaf on top and tuck in!",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=Mt5lgUZRoUg",
        "strIngredient1": "Water",
        "strIngredient2": "Sugar",
        "strIngredient3": "Yeast",
        "strIngredient4": "Plain Flour",
        "strIngredient5": "Salt",
        "strIngredient6": "Olive Oil",
        "strIngredient7": "Passata",
        "strIngredient8": "Mozzarella",
        "strIngredient9": "Oregano",
        "strIngredient10": "Basil",
        "strIngredient11": "Black Pepper",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "150ml",
        "strMeasure2": "1 tsp ",
        "strMeasure3": "15g",
        "strMeasure4": "225g",
        "strMeasure5": "1 1/2 tsp ",
        "strMeasure6": "Drizzle",
        "strMeasure7": "80g",
        "strMeasure8": "70g",
        "strMeasure9": "Peeled and Sliced",
        "strMeasure10": "Leaves",
        "strMeasure11": "Pinch",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "https://www.dailymail.co.uk/femail/food/article-8240361/Pizza-Express-release-secret-recipe-Margherita-Pizza-make-home.html",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
      },  
      {
      "idMeal": "53085",
      "strMeal": "15-minute chicken & halloumi burgers",
      "strDrinkAlternate": null,
      "strCategory": "Chicken",
      "strArea": "American",
      "strInstructions": "STEP 1\r\n\r\nPut the chicken breasts between two pieces of baking parchment and use a rolling pin to gently bash them until they are approximately 1cm thick. Cut each chicken breast into two even pieces.\r\n\r\nSTEP 2\r\n\r\nIf you're using a frying pan, heat two frying pans over medium-high heat, with one of them containing oil. Fry the chicken in the oiled pan for 3-4 mins on each side until they are cooked through. Season the chicken, reduce the heat, drizzle in the chilli sauce and half of the lemon juice, and cook for an additional 1-2 mins until the sauce is reduced. Remove the chicken from the heat.\r\n\r\nSTEP 3\r\n\r\nIf you're using an air-fryer, preheat it to 180C for 4 mins. Add the chicken to the air-fryer and cook for 12 mins. Drizzle over the chilli sauce and half the lemon juice and cook for an additional 1-2 mins until the chicken is cooked through and the sauce is reduced. Remove the chicken and keep it warm.\r\nSTEP 4\r\n\r\nWhile the chicken is cooking, toast the buns in the dry frying pan for 30 seconds. Transfer them to a plate. If you're using an air fryer, put the buns in the air fryer for 1-2 mins until they are warm. Increase the air fryer temperature to 200C. Add the halloumi to the air fryer basket and cook for 10 mins, turning halfway through, until it's golden. Toss the cabbage with the mayo and the remaining lemon juice.\r\n\r\nSTEP 5\r\n\r\nSpoon the hummus (or dip of your choice) into the toasted buns, then top with the rocket, chilli chicken, halloumi, and peppers. Drizzle with a little more chilli sauce, spoon over the cabbage, season with black pepper, and top with the bun lids. Serve with any extra cabbage on the side or a green salad.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/vdwloy1713225718.jpg",
      "strTags": null,
      "strYoutube": "",
      "strIngredient1": "Chicken Breasts",
      "strIngredient2": "Oil",
      "strIngredient3": "Hotsauce",
      "strIngredient4": "Lemon Juice",
      "strIngredient5": "Buns",
      "strIngredient6": "Cheese",
      "strIngredient7": "Cabbage",
      "strIngredient8": "Mayonnaise",
      "strIngredient9": "Sour Cream",
      "strIngredient10": "Lettuce",
      "strIngredient11": "Red Pepper",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2",
      "strMeasure2": "1 tbsp",
      "strMeasure3": "4 tbsp",
      "strMeasure4": "½",
      "strMeasure5": "2",
      "strMeasure6": "250g",
      "strMeasure7": "¼",
      "strMeasure8": "2 tbsp",
      "strMeasure9": "4 tbsp",
      "strMeasure10": "4 leaves",
      "strMeasure11": "2",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/15-minute-chicken-halloumi-burgers",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53083",
      "strMeal": "Lamb Pilaf (Plov)",
      "strDrinkAlternate": null,
      "strCategory": "Lamb",
      "strArea": "Russian",
      "strInstructions": "Place the raisins and prunes into a small bowl and pour over enough water to cover. Add lemon juice and let soak for at least 1 hour. Drain. Roughly chop the prunes.\r\n\r\nMeanwhile, heat the butter in a large pan, add the onion, and cook for 5 minutes. Add cubed lamb, ground lamb, and crushed garlic cloves. Fry for 5 minutes, stirring constantly until browned.\r\n\r\nPour 2/3 cup (150 milliliters) of stock into the pan. Bring to a boil, then lower the heat, cover, and simmer for 1 hour, or until the lamb is tender.\r\n\r\nAdd the remaining stock and bring to a boil. Add rinsed long-grain white rice and a large pinch of saffron. Stir, then cover, and simmer for 15 minutes, or until the rice is tender.\r\n\r\nAdd the drained raisins, drained chopped prunes, and salt and pepper to taste. Heat through for a few minutes, then turn out onto a warmed serving dish and garnish with sprigs of flat-leaf parsley.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/kos9av1699014767.jpg",
      "strTags": "rice",
      "strYoutube": "https://www.youtube.com/watch?v=rllQsUw1hFQ",
      "strIngredient1": "Lamb",
      "strIngredient2": "Prunes",
      "strIngredient3": "Lemon Juice",
      "strIngredient4": "Butter",
      "strIngredient5": "Onion",
      "strIngredient6": "Lamb",
      "strIngredient7": "Garlic",
      "strIngredient8": "Vegetable Stock",
      "strIngredient9": "Rice",
      "strIngredient10": "Saffron",
      "strIngredient11": "Parsley",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "50g",
      "strMeasure2": "120g",
      "strMeasure3": "1 tbs",
      "strMeasure4": "2 tbs",
      "strMeasure5": "1 chopped",
      "strMeasure6": "450g",
      "strMeasure7": "2 cloves",
      "strMeasure8": "600ml",
      "strMeasure9": "2 cups ",
      "strMeasure10": "Pinch",
      "strMeasure11": "Garnish",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.thespruceeats.com/russian-lamb-pilaf-plov-recipe-1137309",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53082",
      "strMeal": "Strawberries Romanoff",
      "strDrinkAlternate": null,
      "strCategory": "Dessert",
      "strArea": "Russian",
      "strInstructions": "In a medium bowl, combine hulled and quartered strawberries, 4 Tbsp sugar and 4 Tbsp liqueur, stir to combine then cover and refrigerate at least 1 hour and up to 2 hours, stirring once or twice.\r\n\r\nTwo photos of cut strawberries in a bowl with one having sugar being added to the bowl Two photos of cut up strawberries for Strawberry Romanoff \r\n\r\nJust before serving, in a large mixing bowl, combine 1 cup cold heavy cream and 1/4 cup powdered sugar, and beat with an electric mixer until stiff peaks form. Using a spatula, fold in 1/4 cup sour cream just until well blended.\r\n\r\nTo serve, stir strawberries then divide between 6 serving glasses or bowls. You can spoon a little syrup over the berries if you like. You can also use this syrup to soak a cake. Spoon cream over strawberries, dividing evenly. You can also use an ice cream scoop with trigger release for a nice rounded puff of cream. Serve right away or chill and enjoy within 2 hours of assembly.\r\n\r\n",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/oe8rg51699014028.jpg",
      "strTags": "fruity",
      "strYoutube": "https://www.youtube.com/watch?v=ybWHc4Vi-xU",
      "strIngredient1": "Strawberries",
      "strIngredient2": "Sugar",
      "strIngredient3": "Grand Marnier",
      "strIngredient4": "Cream",
      "strIngredient5": "Sour Cream",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 pint ",
      "strMeasure2": "4 tbs",
      "strMeasure3": "4 tbs",
      "strMeasure4": "1 cup ",
      "strMeasure5": "1/4 cup",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://natashaskitchen.com/strawberries-romanoff-recipe/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53081",
      "strMeal": "Potato Salad (Olivier Salad)",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Russian",
      "strInstructions": "Cut the potatoes and carrots into small uniform cubes.\r\nPlace them in a large pot and fill with water.\r\nAdd salt and vinegar. Bring it to a boil over medium high heat, and then reduce the heat to medium and continue to cook until the potatoes are cooked through, about 15 minutes. Drain the potatoes and let it cool to room temperature.\r\nMeanwhile, cut the sausage and pickles into small cubes, and chop the green onions.\r\nCut the hard-boiled eggs into small cubes as well.\r\nIf using fresh dill, chop them as well.\r\nIn a large bowl, combine potatoes, carrots, sausage, pickles, peas and green onions.\r\nAdd mayo and dill and mix until well combined.\r\nSalt and pepper to taste. Cover with a plastic wrap and refrigerate for at least 1 hour before serving.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/ebvuir1699013665.jpg",
      "strTags": "salad",
      "strYoutube": "https://www.youtube.com/watch?v=RnsWwHcpKiY",
      "strIngredient1": "Potatoes",
      "strIngredient2": "Carrots",
      "strIngredient3": "Salt",
      "strIngredient4": "White Wine Vinegar",
      "strIngredient5": "Eggs",
      "strIngredient6": "Sausages",
      "strIngredient7": "Dill",
      "strIngredient8": "Peas",
      "strIngredient9": "Onions",
      "strIngredient10": "Mayonnaise",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "4",
      "strMeasure2": "3",
      "strMeasure3": "1 tbs",
      "strMeasure4": "1/2 tbs",
      "strMeasure5": "4",
      "strMeasure6": "7 oz ",
      "strMeasure7": "4 oz ",
      "strMeasure8": "1 can ",
      "strMeasure9": "4",
      "strMeasure10": "1 cup ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.sweetandsavorybyshinee.com/russian-potato-salad/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53080",
      "strMeal": "Blini Pancakes",
      "strDrinkAlternate": null,
      "strCategory": "Side",
      "strArea": "Russian",
      "strInstructions": "In a large bowl, whisk together 1/2 cup buckwheat flour, 2/3 cup all-purpose flour, 1/2 teaspoon salt, and 1 teaspoon yeast.\r\n\r\nMake a well in the center and pour in 1 cup warm milk, whisking until the batter is smooth.\r\n\r\nCover the bowl and let the batter rise until doubled, about 1 hour.\r\n\r\nEnrich and Rest the Batter\r\nStir 2 tablespoons melted butter and 1 egg yolk into the batter.\r\n\r\nIn a separate bowl, whisk 1 egg white until stiff, but not dry.\r\n\r\nFold the whisked egg white into the batter.\r\n\r\nCover the bowl and let the batter stand 20 minutes.\r\n\r\nPan-Fry the Blini\r\nHeat butter in a large nonstick skillet over medium heat.\r\n\r\nDrop quarter-sized dollops of batter into the pan, being careful not to overcrowd the pan. Cook for about 1 minute or until bubbles form.\r\n\r\nTurn and cook for about 30 additional seconds.\r\n\r\nRemove the finished blini onto a plate and cover them with a clean kitchen towel to keep warm. Add more butter to the pan and repeat the frying process with the remaining batter.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/0206h11699013358.jpg",
      "strTags": "pancake",
      "strYoutube": "https://www.youtube.com/watch?v=GsB8ZI5vREA",
      "strIngredient1": "Buckwheat",
      "strIngredient2": "Flour",
      "strIngredient3": "Salt",
      "strIngredient4": "Yeast",
      "strIngredient5": "Milk",
      "strIngredient6": "Butter",
      "strIngredient7": "Egg",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1/2 cup ",
      "strMeasure2": "2/3 Cup",
      "strMeasure3": "1/2 tsp",
      "strMeasure4": "1 tsp ",
      "strMeasure5": "1 cup ",
      "strMeasure6": "2 tbs",
      "strMeasure7": "1 Seperated",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.thespruceeats.com/russian-blini-recipe-buckwheat-pancakes-1136797",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53079",
      "strMeal": "Fish Soup (Ukha)",
      "strDrinkAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Russian",
      "strInstructions": "In a medium pot, heat the olive oil over medium-high heat. Add the onions and cook, stirring occasionally until the onions start to caramelize. Add the carrots and cook until the carrots start to soften, about 4 more minutes.\r\nAdd the stock, water, potatoes, bay leaves, and black peppercorns. Season with salt and bring to a boil. Reduce heat, cover and cook for 10 minutes. Add the millet and cook for 15 more minutes until millet and potatoes are cooked.\r\nGently add the fish cubes. Stir and bring the soup to a simmer. The fish will cook through very fast, so make sure to not overcook them. They are done when the flesh is opaque and flakes easily.\r\nGarnish the soup with chopped fresh dill or parsley before serving.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/7n8su21699013057.jpg",
      "strTags": "soup",
      "strYoutube": "https://www.youtube.com/watch?v=cS3Yn-y5uVg",
      "strIngredient1": "Olive Oil",
      "strIngredient2": "Onion",
      "strIngredient3": "Carrots",
      "strIngredient4": "Fish Stock",
      "strIngredient5": "Water",
      "strIngredient6": "Potatoes",
      "strIngredient7": "Bay Leaf",
      "strIngredient8": "Cod",
      "strIngredient9": "Salmon",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tbs",
      "strMeasure2": "1 sliced",
      "strMeasure3": "2 medium",
      "strMeasure4": "3 cups ",
      "strMeasure5": "3 cups ",
      "strMeasure6": "4 large",
      "strMeasure7": "3",
      "strMeasure8": "1",
      "strMeasure9": "1",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.curiouscuisiniere.com/ukha-russian-fish-soup/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53078",
      "strMeal": "Beetroot Soup (Borscht)",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Ukrainian",
      "strInstructions": "Chop the beetroot, add water and stock cube and cook for 15mins. Add the other ingredients and boil until soft. Finally add the beans and cook for 5mins. Serve in the soup pot.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/zadvgb1699012544.jpg",
      "strTags": "soup",
      "strYoutube": "https://www.youtube.com/watch?v=6CXgPVw_-0g",
      "strIngredient1": "Beetroot",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Chicken Stock Cube",
      "strIngredient4": "Water",
      "strIngredient5": "Potatoes",
      "strIngredient6": "Cannellini Beans",
      "strIngredient7": "Dill",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3",
      "strMeasure2": "4 tbs",
      "strMeasure3": "1",
      "strMeasure4": "6 cups ",
      "strMeasure5": "3",
      "strMeasure6": "1 can ",
      "strMeasure7": "Garnish",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://natashaskitchen.com/classic-russian-borscht-recipe/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53077",
      "strMeal": "Cabbage Soup (Shchi)",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Russian",
      "strInstructions": "Add the butter to a large Dutch oven or other heavy-duty pot over medium heat. When the butter has melted, add the onion and sauté until translucent.\r\nAdd the cabbage, carrot, and celery. Sauté until the vegetables begin to soften, stirring frequently, about 3 minutes.\r\nAdd the bay leaf and vegetable stock and bring to a boil over high heat. Reduce the heat to low and simmer, covered, until the vegetables are crisp-tender, about 15 minutes.\r\nAdd the potatoes and bring it back to a boil over high heat. Reduce the heat to low and simmer, covered, until the potatoes are tender, about 10 minutes.\r\nAdd the tomatoes (or undrained canned tomatoes) and bring the soup back to a boil over high heat. Reduce the heat to low and simmer, uncovered, for 5 minutes. Season to taste with salt and pepper.\r\nemove and discard the bay leaf from the pot.\r\nServe topped with fresh sour cream and fresh dill.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/60oc3k1699009846.jpg",
      "strTags": "soup",
      "strYoutube": "https://www.youtube.com/watch?v=lTjlbqGc_Y8",
      "strIngredient1": "Unsalted Butter",
      "strIngredient2": "Onion",
      "strIngredient3": "Cabbage",
      "strIngredient4": "Carrots",
      "strIngredient5": "Celery",
      "strIngredient6": "Bay Leaf",
      "strIngredient7": "Vegetable Stock",
      "strIngredient8": "Potatoes",
      "strIngredient9": "Tomatoes",
      "strIngredient10": "Sour Cream",
      "strIngredient11": "Dill",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 tbs",
      "strMeasure2": "1 large",
      "strMeasure3": "1 medium",
      "strMeasure4": "1",
      "strMeasure5": "1",
      "strMeasure6": "1",
      "strMeasure7": "8 cups ",
      "strMeasure8": "2 large",
      "strMeasure9": "2 large",
      "strMeasure10": "Garnish",
      "strMeasure11": "Garnish",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.thespruceeats.com/traditional-russian-cabbage-soup-shchi-recipe-1135534",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53076",
      "strMeal": "Bread omelette",
      "strDrinkAlternate": null,
      "strCategory": "Breakfast",
      "strArea": "Indian",
      "strInstructions": "Make and enjoy",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg",
      "strTags": null,
      "strYoutube": "",
      "strIngredient1": "Bread",
      "strIngredient2": "Egg",
      "strIngredient3": "Salt",
      "strIngredient4": "",
      "strIngredient5": "",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2",
      "strMeasure2": "2",
      "strMeasure3": "0.5",
      "strMeasure4": " ",
      "strMeasure5": " ",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53075",
      "strMeal": "Tortang Talong",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Filipino",
      "strInstructions": "0.\tGrill the eggplant until the color of skin turns almost black\r\n1.\tLet the eggplant cool for a while then peel off the skin. Set aside.\r\n2.\tCrack the eggs and place in a bowl\r\n3.\tAdd salt and beat\r\n4.\tPlace the eggplant on a flat surface and flatten using a fork.\r\n5.\tDip the flattened eggplant in the beaten egg mixture\r\n6.\tHeat the pan and pour the cooking oil\r\n7.\tFry the eggplant (that was dipped in the beaten mixture). Make sure that both sides are cooked. Frying time will take you about 3 to 4 minutes per side on medium heat. \r\n",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/va668f1683209318.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=eLl8ekOu1MM",
      "strIngredient1": "Egg Plants",
      "strIngredient2": "Eggs",
      "strIngredient3": "Salt",
      "strIngredient4": "Olive Oil",
      "strIngredient5": "",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "4",
      "strMeasure2": "2",
      "strMeasure3": "1 tsp ",
      "strMeasure4": "4 tsp",
      "strMeasure5": " ",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.sainsburysmagazine.co.uk/recipes/mains/tortang-talong",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },

]